### ISSUE TITLE
File table Schema Update Hook

### ISSUE THREAD

**Issue by djstreat** [simsong/NativeFileList#2]
From email:
It should have an update hook that creates the file table schema if it is not present.

**Comment by djstreat** [comment]
@simsong Did you have any other hooks in mind for when it should run this check, or should I add code for this check to be run before every search (onSpecialSearchResultsAppend)?

**Comment by simsong** [comment]
It needs to implement the `LoadExtensionSchemaUpdates` hook. See:
* https://www.mediawiki.org/wiki/Manual:Hooks/LoadExtensionSchemaUpdates
* https://stackoverflow.com/questions/58680500/proper-way-to-create-new-sql-table-in-a-mediawiki-extension/58683843#58683843

As long as we are implementing this, we should implement it the right way!

Currently on the server it is quite slow to do the file search after each search, which is why I want to do it asynchronously on the production machine.   But I suspect that search will be faster when it uses the proper search API.

It would be great if you could implement Special pages for Recent Files Changed in S3/Native File System, and Recent Files Deleted.

**Comment by djstreat** [comment]
Just to clarify, I should be creating a totally new schema/database for the tables related to the scanner and filechange programs, correct? As in, the server should contain the schemas `mediawiki` and `das_s3bucket`?

The reason I ask is because the functions related to the `DatabaseUpdater.php`([link](https://www.mediawiki.org/wiki/Manual:DatabaseUpdater.php)) don't seem to be able to affect schemas other than the one defined by the wiki, in this case `mediawiki`. 

If this is the case, then I should just add the new tables to the `mediawiki` schema that can be modified by the extension scripts. 

Just trying to see if I am on the right track about this issue.

**Comment by djstreat** [comment]
Quick update: I think my assumption from the previous comment was woefully incorrect. I don't see any syntax in the mediawiki documentation to add new schemas or interact with schemas outside of the mediawiki-specific schema. Since that's the case, I'm going to move in that direction and create the new tables within the mediawiki schema.

**Comment by simsong** [comment]
You can create tables in the update hook that I mentioned. you can also reference tables and other databases by using the databasename.table notation.


----
Sent from my phone.

> On Nov 19, 2019, at 1:19 PM, djstreat <notifications@github.com> wrote:
> 

﻿
Quick update: I think my assumption from the previous comment was woefully incorrect. I don't see any syntax in the mediawiki documentation to add new schemas or interact with schemas outside of the mediawiki-specific schema. Since that's the case, I'm going to move in that direction and create the new tables within the mediawiki schema.

**Comment by djstreat** [comment]
I wanted to post a quick update: It seems like some of the documentation on MariaDB is not quite correct in that it [states](https://mariadb.com/kb/en/library/grant/#database-privileges) "You can grant the CREATE privilege on databases that do not yet exist. This also grants the CREATE privilege on all tables in the database."

However, this gives me a `database does not exist` error. [What I think i have to do is give the wiki's mysql user all privileges in all databases](https://stackoverflow.com/questions/6450192/cant-create-databases-with-a-new-user) which seems a tad unsafe. Wanted to hear your thoughts on this.

**Comment by simsong** [comment]
Typically, the mysql/mariadb user that runs the update script has full access to the database, with only the `CREATE DATABASE` command being denied.
